.TH "Bimap< X, Y >" 3 "Thu Feb 20 2014" "Version 0.0.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bimap< X, Y > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'bimap\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBimap\fP ()"
.br
.ti -1c
.RI "\fBBimap\fP (const std::map< X, Y > &m)"
.br
.ti -1c
.RI "void \fBupdate_from_map\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map< X, Y > \fBto\fP"
.br
.ti -1c
.RI "std::map< Y, X > \fBfrom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename X, typename Y>struct Bimap< X, Y >"

.PP
Definition at line 6 of file bimap\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename X, typename Y> \fBBimap\fP< X, Y >::\fBBimap\fP ()\fC [inline]\fP"

.PP
Definition at line 9 of file bimap\&.hpp\&.
.SS "template<typename X, typename Y> \fBBimap\fP< X, Y >::\fBBimap\fP (const std::map< X, Y > &m)\fC [inline]\fP"

.PP
Definition at line 10 of file bimap\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename X, typename Y> void \fBBimap\fP< X, Y >::update_from_map ()\fC [inline]\fP"

.PP
Definition at line 13 of file bimap\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename X, typename Y> std::map<Y,X> \fBBimap\fP< X, Y >::from"

.PP
Definition at line 8 of file bimap\&.hpp\&.
.SS "template<typename X, typename Y> std::map<X,Y> \fBBimap\fP< X, Y >::to"

.PP
Definition at line 7 of file bimap\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
