.TH "Open-Horizons/bimap.hpp" 3 "Fri Mar 7 2014" "Version 0.0.1.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Open-Horizons/bimap.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBimap< X, Y >\fP"
.br
.RI "\fI< Define a generic bimap type (X <-> Y) Specialized bimap type (E_DRIVER_TYPE <-> string) \fP"
.ti -1c
.RI "struct \fBIrrDriversBimap\fP"
.br
.RI "\fIBIMAP_HPP_INCLUDED\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
