.TH "Open-Horizons/DriverSelectionConfiguration.hpp" 3 "Thu Feb 20 2014" "Version 0.0.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Open-Horizons/DriverSelectionConfiguration.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inisetup\&.hpp'\fP
.br
\fC#include <limits>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <functional>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfatal\fP (const char *error, int exit_code)"
.br
.ti -1c
.RI "void \fBPlay_Now\fP ()"
.br
.ti -1c
.RI "void \fBAdvanced_Options\fP ()"
.br
.ti -1c
.RI "void \fBMulitplayerInfo\fP ()"
.br
.ti -1c
.RI "void \fBdisplay_software_select\fP ()"
.br
.ti -1c
.RI "void \fBoptional_config\fP ()"
.br
.ti -1c
.RI "void \fBoptions_select\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBchoose_switch_stuff\fP"
.br
.ti -1c
.RI "int \fBcolour_bits\fP = 32"
.br
.ti -1c
.RI "bool \fBfullscreen_define\fP = false"
.br
.ti -1c
.RI "bool \fBshadows_define\fP = true"
.br
.ti -1c
.RI "bool \fBvsync_define\fP = false"
.br
.ti -1c
.RI "int \fBscreen_width\fP"
.br
.ti -1c
.RI "int \fBscreen_height\fP"
.br
.ti -1c
.RI "std::string \fBipaddress\fP"
.br
.ti -1c
.RI "int \fBportnumber\fP"
.br
.ti -1c
.RI "irr::video::E_DRIVER_TYPE \fBdisplay_software\fP"
.br
.ti -1c
.RI "std::string \fBdisplay_software_string\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Advanced_Options ()"

.PP
Definition at line 59 of file DriverSelectionConfiguration\&.hpp\&.
.SS "void display_software_select ()"

.PP
Definition at line 134 of file DriverSelectionConfiguration\&.hpp\&.
.SS "void fatal (const char *error, intexit_code)"

.PP
Definition at line 29 of file DriverSelectionConfiguration\&.hpp\&.
.SS "void MulitplayerInfo ()"

.PP
Definition at line 117 of file DriverSelectionConfiguration\&.hpp\&.
.SS "void optional_config ()"

.PP
Definition at line 241 of file DriverSelectionConfiguration\&.hpp\&.
.SS "void options_select ()"

.PP
Definition at line 264 of file DriverSelectionConfiguration\&.hpp\&.
.SS "void Play_Now ()"

.PP
Definition at line 35 of file DriverSelectionConfiguration\&.hpp\&.
.SH "Variable Documentation"
.PP 
.SS "char choose_switch_stuff"

.PP
Definition at line 8 of file DriverSelectionConfiguration\&.hpp\&.
.SS "int colour_bits = 32"

.PP
Definition at line 10 of file DriverSelectionConfiguration\&.hpp\&.
.SS "irr::video::E_DRIVER_TYPE display_software"

.PP
Definition at line 22 of file DriverSelectionConfiguration\&.hpp\&.
.SS "std::string display_software_string"

.PP
Definition at line 27 of file DriverSelectionConfiguration\&.hpp\&.
.SS "bool fullscreen_define = false"

.PP
Definition at line 11 of file DriverSelectionConfiguration\&.hpp\&.
.SS "std::string ipaddress"

.PP
Definition at line 18 of file DriverSelectionConfiguration\&.hpp\&.
.SS "int portnumber"

.PP
Definition at line 20 of file DriverSelectionConfiguration\&.hpp\&.
.SS "int screen_height"

.PP
Definition at line 16 of file DriverSelectionConfiguration\&.hpp\&.
.SS "int screen_width"

.PP
Definition at line 15 of file DriverSelectionConfiguration\&.hpp\&.
.SS "bool shadows_define = true"

.PP
Definition at line 12 of file DriverSelectionConfiguration\&.hpp\&.
.SS "bool vsync_define = false"

.PP
Definition at line 13 of file DriverSelectionConfiguration\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
