.TH "Open-Horizons/EventReceiver.hpp" 3 "Fri Mar 7 2014" "Version 0.0.1.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Open-Horizons/EventReceiver.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <irrlicht/irrlicht\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventReceiver\fP"
.br
.RI "\fIEVENTRECEIVER_HPP_INCLUDED\&. \fP"
.ti -1c
.RI "struct \fBEventReceiver::SMouseState\fP"
.br
.RI "\fI< We'll create a struct to record info on the mouse state \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
