.TH "EventReceiver::SMouseState" 3 "Thu Feb 20 2014" "Version 0.0.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventReceiver::SMouseState \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'EventReceiver\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSMouseState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "core::position2di \fBPosition\fP"
.br
.ti -1c
.RI "bool \fBLeftButtonDown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file EventReceiver\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EventReceiver::SMouseState::SMouseState ()\fC [inline]\fP"

.PP
Definition at line 18 of file EventReceiver\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "bool EventReceiver::SMouseState::LeftButtonDown"

.PP
Definition at line 17 of file EventReceiver\&.hpp\&.
.SS "core::position2di EventReceiver::SMouseState::Position"

.PP
Definition at line 16 of file EventReceiver\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
