.TH "inisetup::empty_class" 3 "Thu Feb 20 2014" "Version 0.0.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inisetup::empty_class \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'inisetup\&.hpp'\fP
.SH "Detailed Description"
.PP 
Definition at line 42 of file inisetup\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
