.TH "Open-Horizons/inisetup.hpp" 3 "Fri Mar 7 2014" "Version 0.0.1.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Open-Horizons/inisetup.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <stdexcept>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinisetup::empty_class\fP"
.br
.RI "\fIThis holds the mapping (option name -> setting) \fP"
.ti -1c
.RI "class \fBinisetup::IniSetup\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBinisetup\fP"
.br
.RI "\fI< This library was written by Michele Bini in 2014 and placed in the public domain \fP"
.in -1c
.SS "Constant Groups"

.in +1c
.ti -1c
.RI "\fBinisetup\fP"
.br
.RI "\fI< This library was written by Michele Bini in 2014 and placed in the public domain \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "map< string, string > \fBinisetup::_m\fP"
.br
.ti -1c
.RI "map< string, string > \fBinisetup::_settings_on_file\fP"
.br
.ti -1c
.RI "map< string, empty_class > \fBinisetup::_possibly_changed_settings\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
