.TH "inisetup" 3 "Thu Feb 20 2014" "Version 0.0.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inisetup \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBempty_class\fP"
.br
.ti -1c
.RI "class \fBIniSetup\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "map< string, string > \fB_m\fP"
.br
.ti -1c
.RI "map< string, string > \fB_settings_on_file\fP"
.br
.ti -1c
.RI "map< string, \fBempty_class\fP > \fB_possibly_changed_settings\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "map<string, string> inisetup::_m"

.PP
Definition at line 44 of file inisetup\&.hpp\&.
.SS "map<string, \fBempty_class\fP> inisetup::_possibly_changed_settings"

.PP
Definition at line 46 of file inisetup\&.hpp\&.
.SS "map<string, string> inisetup::_settings_on_file"

.PP
Definition at line 45 of file inisetup\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
