.TH "IrrDriversBimap" 3 "Fri Mar 7 2014" "Version 0.0.1.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IrrDriversBimap \- 
.PP
BIMAP_HPP_INCLUDED\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'bimap\&.hpp'\fP
.PP
Inherits \fBBimap< irr::video::E_DRIVER_TYPE, std::string >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIrrDriversBimap\fP ()"
.br
.ti -1c
.RI "void \fBupdate_from_map\fP ()"
.br
.RI "\fIBuild up the 'from' map (Y -> X) using the 'to' map (X -> Y) \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::map
.br
< irr::video::E_DRIVER_TYPE, 
.br
std::string > \fBto\fP"
.br
.ti -1c
.RI "std::map< std::string, 
.br
irr::video::E_DRIVER_TYPE > \fBfrom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BIMAP_HPP_INCLUDED\&. 
.PP
Definition at line 25 of file bimap\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IrrDriversBimap::IrrDriversBimap ()\fC [inline]\fP"

.PP
Definition at line 26 of file bimap\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBBimap\fP< irr::video::E_DRIVER_TYPE , std::string  >::update_from_map ()\fC [inline]\fP, \fC [inherited]\fP"

.PP
Build up the 'from' map (Y -> X) using the 'to' map (X -> Y) <Exclamation mark means negation, //!<I\&.E !true = false or !!true == true\&. 
.PP
Definition at line 14 of file bimap\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "std::map<std::string ,irr::video::E_DRIVER_TYPE > \fBBimap\fP< irr::video::E_DRIVER_TYPE , std::string  >::from\fC [inherited]\fP"

.PP
Definition at line 9 of file bimap\&.hpp\&.
.SS "std::map<irr::video::E_DRIVER_TYPE ,std::string > \fBBimap\fP< irr::video::E_DRIVER_TYPE , std::string  >::to\fC [inherited]\fP"

.PP
Definition at line 8 of file bimap\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
