.TH "Open-Horizons/main.cpp" 3 "Thu Feb 20 2014" "Version 0.0.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Open-Horizons/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <irrlicht\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'inisetup\&.hpp'\fP
.br
\fC#include 'bimap\&.hpp'\fP
.br
\fC#include 'EventReceiver\&.hpp'\fP
.br
\fC#include 'DriverSelectionConfiguration\&.hpp'\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'UDPSocket\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 19 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
