.TH "md_Open-Horizons_README" 3 "Fri Mar 7 2014" "Version 0.0.1.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_Open-Horizons_README \- Open-Horizons 
From Stones to Stars!
.PP
A game of realism and simulation!
.PP
This is a game using the Irrlicht Engine,
.PP
http://irrlicht.sourceforge.net/
.PP
(Some art from the Irrlicht tutorials, I\&.E the quake 3 level have been temporarily used for testing purposes, This is not permanent! I do not, Nor does anyone working on Open Horizons, Claim to own or have created any of the art work in any way, Shape, Or form\&. It will soon be removed\&.)
.PP
Open Horizons has very ambitons, Yet, I think, Obtainable goals, Such as a simulation based health system, Rather than hit point based\&. I\&.E Instead of having a set number of blood 'points' which is exactly the same for everyone, Which are removed by an exact amount based on actions which always happen in the same way, (I\&.E being shot in a certian place) Blood, For example, In Open Horizons, Would be simulated with liquid dynamics\&. So, A heart pumps which is governed by physics, Not something that was contrived\&. Blood flows according to liquid dynamics, And spills out according to liquid dynamics, In conjunction with blood cloats to stop the bleeding\&. All governed by liquid dynamics, And physics\&. All realistic, All unique\&.
.PP
.SH "If you enjoy soft body physics in racing games, You'll LOVE Open Horizons! "
.PP
.PP
Please note: Open Horizons is currently in unbelievely early pre-alpha, If you are looking for examples of what I have explained above, You will have to wait for a little while longer\&. I'm sorry\&. :(
.PP
.SH "Build Instructions "
.PP
.PP
Coming soon! 
