.TH "ServAddr" 3 "Fri Mar 7 2014" "Version 0.0.1.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServAddr \- 
.PP
< \fBUDPSocket\&.hpp\fP - An OO representation of UDP connections  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'UDPSocket\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServAddr\fP (const char *addr, int port)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct sockaddr_in \fBservaddr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
< \fBUDPSocket\&.hpp\fP - An OO representation of UDP connections 

< Version: 0\&.4 < Standard C header files, needed for the structures and system calls below (e\&.g\&. socket, recvfrom, sendto, \&.\&.\&.) < Represents a remote host + port number 
.PP
Definition at line 22 of file UDPSocket\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ServAddr::ServAddr (const char *addr, intport)\fC [inline]\fP"

.PP
Definition at line 24 of file UDPSocket\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "struct sockaddr_in ServAddr::servaddr"

.PP
Definition at line 23 of file UDPSocket\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
