.TH "ServAddr" 3 "Thu Feb 20 2014" "Version 0.0.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServAddr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'UDPSocket\&.hpp'\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServAddr\fP (const char *addr, int port)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct sockaddr_in \fBservaddr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file UDPSocket\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ServAddr::ServAddr (const char *addr, intport)\fC [inline]\fP"

.PP
Definition at line 23 of file UDPSocket\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "struct sockaddr_in ServAddr::servaddr"

.PP
Definition at line 22 of file UDPSocket\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
