.TH "Open-Horizons/UDPSocket.hpp" 3 "Fri Mar 7 2014" "Version 0.0.1.1" "Open Horizons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Open-Horizons/UDPSocket.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBServAddr\fP"
.br
.RI "\fI< \fBUDPSocket\&.hpp\fP - An OO representation of UDP connections \fP"
.ti -1c
.RI "struct \fBUDPSocket\fP"
.br
.RI "\fIExample usage: \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Open Horizons from the source code\&.
